apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: vprofile/vprofiledb:V1
        ports:
        - name: vprodb-port
          containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-node-2
      volumes:
      - name: vpro-db-data
        persistentVolumeClaim:
          claimName: local-pvc
      initContainers:
      - name: busybox
        image: busybox:latest
        args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: vpro-db-data
          mountPath: /var/lib/mysql

